- name: Update package lists
  apt:
    update_cache: true
  become: yes

- name: Install Python 3 pip
  package:
    name:
      - python3-pip
      - python3-setuptools
      - python3-venv
      - python3-wheel
  become: yes

- name: Install Python 2 pip
  package:
    name:
      - python-setuptools
      - python-pip
      - python-wheel
  become: yes
  when: ensure_pip_from_packages_with_python2
