- name: Install Python 3 pip
  package:
    name:
      - python3-pip
      - python3-wheel
  become: yes

- name: Install Python 2 pip
  package:
    name:
      - python2-pip
      - python2-wheel
  become: yes
  when: ensure_pip_from_packages_with_python2
