zuul_build_sshkey_cleanup: false
zuul_ssh_key_algorithm: "rsa"
zuul_ssh_key_size: "3072"
zuul_ssh_key_dest: "id_{{ zuul_ssh_key_algorithm }}"
zuul_temp_ssh_key: "{{ zuul.executor.work_root }}/{{ zuul.build }}_id_{{ zuul_ssh_key_algorithm }}"
