- name: Set log path for multiple nodes
  set_fact:
    log_path: "{{ zuul.executor.log_root }}/{{ inventory_hostname }}"
  when: groups['all'] | length > 1

- name: Set log path for single node
  set_fact:
    log_path: "{{ zuul.executor.log_root }}"
  when: log_path is not defined

- name: Ensure local output dirs
  delegate_to: localhost
  file:
    path: "{{ zj_output_dir }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ log_path }}"
    - "{{ log_path }}/npm"
    - "{{ zuul.executor.work_root }}/artifacts"
    - "{{ zuul.executor.work_root }}/docs"
  loop_control:
    loop_var: zj_output_dir

- name: Include rsync tasks
  include_tasks: rsync.yaml
  when: zj_pod.1.pod is defined
  loop: "{{ openshift_pods.items()|list }}"
  loop_control:
    loop_var: zj_pod
  run_once: true

- name: Remove empty directory
  command: find "{{ zuul.executor.work_root }}" -empty -type d -delete
  delegate_to: localhost
