---
chart_testing_version: 2.4.0
ensure_chart_testing_repo_name_helm_chart: "https://github.com/helm/chart-testing/releases/download"
ensure_chart_testing_repo_name_config: "https://raw.githubusercontent.com/helm/chart-testing"
