---
prometheus-mysql-exporter:
  - 0.0.1 Initial Chart
  - 0.0.2 Add 2024.1 overrides
  - 0.0.3 Use quay.io/airshipit/kubernetes-entrypoint:latest-ubuntu_focal by default
  - 0.0.4 Fix typo in the values_overrides directory name
...
