---
- hosts: all
  tasks:
    - name: Put keys to .ssh/authorized_keys
      lineinfile:
        path: /home/zuul/.ssh/authorized_keys
        state: present
        line: "{{ item }}"
      loop:
        - "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMyM6sgu/Xgg+VaLJX5c6gy6ynYX7pO7XNobnKotYRulcEkmiLprvLSg+WP25VDAcSoif3rek3qiVnEYh6R2/Go= vlad@russell"
...
