- name: Rename tarball for uploading
  shell: |
    mkdir -p {{ zuul_output_dir }}/artifacts
    cp *.tgz {{ zuul_output_dir }}/artifacts/{{ zuul.project.short_name }}-{{ project_ver }}.tar.gz
    cp *.tgz {{ zuul_output_dir }}/artifacts/{{ zuul.project.short_name }}-latest.tar.gz
  args:
    chdir: "{{ zuul_work_dir }}"
  tags:
    # Ignore ANSIBLE0007: No need to use file module instead of mkdir
    - skip_ansible_lint

- name: Return artifacts
  when: not zuul_use_fetch_output
  block:
    - name: Ensure artifacts directory exists
      file:
        path: "{{ zuul.executor.work_root }}/artifacts"
        state: directory
        mode: 0755
      delegate_to: localhost

    - name: Collect artifacts
      synchronize:
        dest: "{{ zuul.executor.work_root }}/artifacts/"
        mode: pull
        src: "{{ zuul_output_dir }}/artifacts/"
        verify_host: true
        owner: no
        group: no
