---
- name: Create src directory
  command: >
    oc --context "{{ zj_pod.1.context }}"
       --namespace "{{ zj_pod.1.namespace }}"
       exec {{ zj_pod.1.pod }} mkdir src
  delegate_to: localhost

- name: Copy src repos to the pod
  command: >
    oc --context "{{ zj_pod.1.context }}"
       --namespace "{{ zj_pod.1.namespace }}"
        rsync -q --progress=false
          {{ zuul.executor.src_root }}/
          {{ zj_pod.1.pod }}:src/
  no_log: true
  delegate_to: localhost
