- name: Run hlint
  block:
    - name: Run hlint
      command: "hlint --report={{ report_location }} ."
      vars:
        report_location: "{{ ansible_user_dir }}/zuul-output/logs/{{ hlint_report_name }}"
      args:
        chdir: "{{ zuul_work_dir }}"

  always:
    - name: Return report to Zuul
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: "HLint report"
                url: "{{ hlint_report_name }}"
