package_mirror: "{{ http_or_https }}://{{ mirror_fqdn }}/{{ ansible_distribution | lower }}"
epel_mirror: "{{ http_or_https }}://{{ mirror_fqdn }}/epel"
wheel_mirror: "{{ http_or_https }}://{{ mirror_fqdn }}/wheel/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}-{{ ansible_architecture | lower }}"
