- hosts: all
  tasks:

    - name: Run ensure-docker role
      include_role:
        name: ensure-docker

    - name: Validate docker pull
      command: |
        docker pull --quiet curlimages/curl:latest

    - name: Validate docker host network containers have internet access
      command: |
        docker run --rm --network=host curlimages/curl:latest --no-progress-meter https://httpbin.org/get

    - name: Validate docker default bridge networking containers have internet access
      command: |
        docker run --rm curlimages/curl:latest --no-progress-meter https://httpbin.org/get
