- name: Set up siblings
  include_tasks: siblings.yaml

- name: Build a docker image
  vars:
    tag_prefix: "{{ ('change_' + zuul.change) if (zuul.change is defined) else zuul.pipeline }}_"
  command: >-
    docker build {{ zj_image.path | default('.') }} -f {{ zj_image.dockerfile | default(docker_dockerfile) }}
    {% if zj_image.target | default(false) -%}
      --target {{ zj_image.target }}
    {% endif -%}
    {% for build_arg in zj_image.build_args | default([]) -%}
      --build-arg {{ build_arg }}
    {% endfor -%}
    {% if zj_image.siblings | default(false) -%}
      --build-arg "ZUUL_SIBLINGS={{ zj_image.siblings | join(' ') }}"
    {% endif -%}
    {% for tag in zj_image.tags | default(['latest']) -%}
      --tag {{ docker_registry | ternary(docker_registry + '/', '') }}{{ zj_image.repository }}:{{ tag_prefix }}{{ tag }}
      --tag {{ docker_registry | ternary(docker_registry + '/', '') }}{{ zj_image.repository }}:{{ tag }}
    {% endfor -%}
    {% for label in zj_image.labels | default([]) -%}
      --label "{{ label }}"
    {% endfor %}
    {% if zuul.change | default(false) -%}
      --label "org.zuul-ci.change={{ zuul.change }}"
    {% endif -%}
    --label "org.zuul-ci.change_url={{ zuul.change_url }}"
  args:
    chdir: "{{ zuul_work_dir }}/{{ zj_image.context }}"
  environment:
    DOCKER_BUILDKIT: '{{ "1" if docker_use_buildkit else "0" }}'

- name: Cleanup sibling source directory
  include_tasks: clean-siblings.yaml
