- name: Require npm_command variable
  fail:
    msg: npm_command is required for this role
  when: npm_command is not defined

- name: Run npm
  include_role:
    name: js-package-manager
  vars:
    js_build_command: '{{ npm_command }}'
    js_build_tool: 'npm'
