- name: Generate Zuul manifest
  generate_manifest:
    root: "{{ generate_zuul_manifest_root }}"
    output: "{{ generate_zuul_manifest_output }}"
    index_links: "{{ generate_zuul_manifest_index_links }}"

- name: Return Zuul manifest URL to Zuul
  zuul_return:
    data:
      zuul:
        artifacts:
          - name: Zuul Manifest
            url: "{{ generate_zuul_manifest_filename }}"
            metadata:
              type: "{{ generate_zuul_manifest_type }}"
