- name: Ensure Zuul Ansible directory exists
  delegate_to: localhost
  run_once: true
  file:
    path: "{{ zuul_info_dir }}"
    state: directory
    mode: 0755

# We don't use the ansible inventory_file variable because it is not defined
# for nodeless job running on the executor directly:
# https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.4.html#inventory
- name: Copy ansible inventory to logs dir
  delegate_to: localhost
  copy:
    src: "{{ zuul.executor.inventory_file }}"
    dest: "{{ zuul_info_dir }}"
    mode: 0644
