---
- name: Install golangci-lint
  become: true
  unarchive:
    remote_src: true
    src: "https://github.com/golangci/golangci-lint/releases/download/v{{ golangci_lint_version }}/golangci-lint-{{ golangci_lint_version }}-linux-amd64.tar.gz"
    dest: /usr/local/bin
    extra_opts:
      - --strip-components=1
