{% if item.skip_server is not defined or not item.skip_server %}
server = "{{ item.server | default('https://' + item.namespace) }}"
{% endif %}

[host."{{ item.mirror }}"]
capabilities = ["pull", "resolve", "push"]
{% if item.ca is defined %}
ca = "{{ item.ca }}"
{% endif %}
{% if item.skip_verify is defined and item.skip_verify %}
skip_verify = true
{% endif %}
