---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
ipvs:
  strictARP: true
...
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  serviceSubnet: "{{ kubeadm.service_cidr }}"  # --service-cidr
  podSubnet: "{{ kubeadm.pod_network_cidr }}"  # --pod-network-cidr
  dnsDomain: "cluster.local"
...
