- name: Install iptables-persistent
  become: yes
  package:
    name: iptables-persistent
    state: present

- name: Persist ipv4 rules
  become: yes
  copy:
    content: "{{ iptables_rules.stdout }}"
    dest: "/etc/iptables/rules.v4"
    mode: 0644

- name: Persist ipv6 rules
  become: yes
  copy:
    content: "{{ ip6tables_rules.stdout }}"
    dest: "/etc/iptables/rules.v6"
    mode: 0644

- name: Ensure netfilter-persistent is started
  become: yes
  service:
    name: netfilter-persistent
    state: started
    enabled: yes
