- name: Check for twine install
  shell: |
    command -v {{ twine_executable }} ~/.local/bin/twine || exit 1
  args:
    executable: /bin/bash
  failed_when: false
  register: register_twine

- name: Set pypi_twine_executable
  set_fact:
    pypi_twine_executable: "{{ register_twine.stdout_lines[0] }}"
  when: register_twine.rc == 0

- name: Ensure twine is installed
  when: register_twine.rc != 0
  block:
    - name: Ensure twine is installed
      command: "{{ twine_python }} -m pip install twine!=1.12.0 requests-toolbelt!=0.9.0 --user"

    - name: Set pypi_twine_executable
      set_fact:
        pypi_twine_executable: ~/.local/bin/twine
