- name: Build a tarball and wheel
  command: "{{ release_python }} setup.py sdist bdist_wheel {{ bdist_wheel_xargs }}"
  args:
    chdir: "{{ zuul_work_dir }}"
  when: build_wheel
- name: Just build a tarball
  command: "{{ release_python }} setup.py sdist"
  args:
    chdir: "{{ zuul_work_dir }}"
  when: not build_wheel
