- hosts: all
  tasks:
    - name: Install binary dependencies
      include_role:
        name: bindep
      vars:
        bindep_dir: "{{ zuul_work_dir }}"
      # TODO don't make this runtime specific
      when: (tox_install_bindep | default(true)) and (nox_install_bindep | default(true))
    - name: Run test-setup role
      include_role:
        name: test-setup
