- hosts: all
  name: Install kubernetes with minikube
  roles:
    - role: ensure-kubernetes
      vars:
        minikube_dns_resolvers:
          - '1.1.1.1'
          - '8.8.8.8'
        ensure_kubernetes_bin_path: /usr/local/bin
