- hosts: all
  name: Install kubernetes with minikube
  roles:
    - role: ensure-kubernetes
      vars:
        minikube_dns_resolvers:
          - '1.1.1.1'
          - '8.8.8.8'
        kubernetes_runtime: podman
        ensure_kubernetes_minikube_addons:
          - ingress
        ensure_kubernetes_bin_path: /usr/local/bin
  post_tasks:
    - name: Check minikube version
      command: minikube version
