- name: Install Bazel dependencies
  become: true
  package:
    name:
      - pkg-config
      - zip
      - g++
      - zlib1g-dev
      - unzip
      - python3
    state: present

- name: Install bazel on Debian
  become: true
  shell: |
    set -ex
    {{ bazel_installer_tempdir.path }}/bazel-{{ bazel_version }}-installer-linux-x86_64.sh
    bazel version
  args:
    executable: /bin/bash
