---
zuul_executor_dest: "{{ zuul.executor.log_root }}"
zuul_work_dir: "{{ zuul.project.src_dir }}"
zuul_output_dir: "{{ ansible_user_dir }}/zuul-output"
zuul_use_fetch_output: "{{ zuul_site_use_fetch_output | default(false) }}"
sphinx_build_dir: doc/build
sphinx_output_suffix: ""
sphinx_output_src: "{{ zuul_work_dir }}/{{ sphinx_build_dir }}/html{{ sphinx_output_suffix }}"
