- hosts: all
  roles:
    - ensure-dib
    - role: build-diskimage
      build_diskimage_image_name: foo-ubuntu-image
      build_diskimage_formats: ["qcow2"]
      build_diskimage_elements: ["vm", "ubuntu"]
      build_diskimage_environment:
        DIB_RELEASE: "noble"
  tasks:
    - name: Gather image file info
      stat:
        path: "/home/zuul/dib-images/foo-ubuntu-image.qcow2"
      register: image_file
    - name: Assert image file exists
      assert:
        that: image_file.stat.exists
