---
# Copyright 2018 SUSE LINUX GmbH.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    templates:
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-helm-lint
        - openstack-helm-lint-osh
        - openstack-helm-infra-bandit
        - openstack-helm-infra-logging
        - openstack-helm-infra-monitoring
        - openstack-helm-infra-metacontroller
        - openstack-helm-infra-mariadb-operator-2024-1-ubuntu_jammy
        - openstack-helm-infra-compute-kit-ovn-2024-1-ubuntu_jammy
        - openstack-helm-infra-compute-kit-2024-1-ubuntu_jammy
        - openstack-helm-infra-cinder-2023-1-ubuntu_focal  # legacy Ceph
        - openstack-helm-infra-cinder-2024-1-ubuntu_jammy
        - openstack-helm-infra-tls-2024-1-ubuntu_jammy
        - openstack-helm-infra-compute-kit-dpdk-2024-1-ubuntu_jammy  # 32GB node
        - openstack-helm-infra-keystone-cilium-2024-1-ubuntu_jammy
        - openstack-helm-infra-keystone-flannel-2024-1-ubuntu_jammy
        - openstack-helm-infra-ceph-migrate
    gate:
      jobs:
        - openstack-helm-lint
        - openstack-helm-lint-osh
        - openstack-helm-infra-logging
        - openstack-helm-infra-monitoring
        - openstack-helm-infra-metacontroller
    post:
      jobs:
        - publish-openstack-helm-charts
    periodic:
      jobs:
        - publish-openstack-helm-charts

...
