- name: Run stack build {{ _stack_build_args }}
  command: "stack build {{ _stack_build_args }}"
  args:
    chdir: "{{ zuul_work_dir }}"

- name: Run stack test {{ _stack_test_args }}
  command: "stack test {{ _stack_test_args }}"
  args:
    chdir: "{{ zuul_work_dir }}"
