- hosts: all
  pre_tasks:
    # Run ensure-output-dirs now as it is not performed speculatively
    - name: Run ensure-output-dirs
      import_role:
        name: ensure-output-dirs

    - name: Create fake translation
      shell: |
        mkdir -p src/{{ zuul.project.canonical_name }}/translation-source/
        echo Hello > src/{{ zuul.project.canonical_name }}/translation-source/test
      tags:
        - skip_ansible_lint

  tasks:
    - name: Run fetch-translation-output
      import_role:
        name: fetch-translation-output

    - name: Run fetch-output
      import_role:
        name: fetch-output
      when: zuul_use_fetch_output

  post_tasks:
    - name: Check for artifact on the test instance
      stat:
        path: "{{ ansible_user_dir }}/zuul-output/artifacts/test"
      register: _test_artifact
      failed_when: not _test_artifact.stat.exists
      when: zuul_use_fetch_output

    - name: Check for artifact on the executor
      stat:
        path: "{{ zuul.executor.work_root }}/artifacts/test"
      delegate_to: localhost
      register: _executor_artifact
      failed_when: not _executor_artifact.stat.exists
