---
dependencies:
  static:
    grafana:
      jobs: null
      services: null
manifests:
  job_db_init: false
  job_db_init_session: false
  job_db_session_sync: false
  job_image_repo_sync: true
  job_run_migrator: false
  job_set_admin_user: false
  secret_db: false
  secret_db_session: false
conf:
  grafana:
    database:
      type: sqlite3
      path: /var/lib/grafana/data/sqlite3.db
    session:
      provider: file
      provider_config: sessions
...
