- name: Ensure project artifact directory exists
  file:
    path: "{{ zuul_fileserver_project_path }}"
    state: directory
    recurse: yes
    mode: 0775

- name: Upload contents of the artifacts folder
  synchronize:
    src: "{{ zuul.executor.work_root }}/artifacts/"
    dest: "{{ zuul_fileserver_project_path }}/"
    owner: no
    group: no
